# vim:ts=2:sw=2:sts=0:number:expandtab
language: c

env:
  matrix:
    - OS_TYPE=debian OS_VERSION=8 BRANCH=devel
    - OS_TYPE=ubuntu OS_VERSION=16.10 BRANCH=devel

services:
  - docker

before_install:
  - docker pull ${OS_TYPE}:${OS_VERSION}

script:
  - docker run --rm --interactive --tty --volume=$PWD:$PWD ${OS_TYPE}:${OS_VERSION} bash -c "cd $PWD && bash .travis.sh --branch ${BRANCH} --nox11rdp --noinstall"

